### PR TITLE
Add feature to disable reset of animation

### PR DESCRIPTION
**Pull request by ramasilveyra**
Add feature to disable reset of animation. Semver minor change.

### CODE REVIEW

**Comment by graingert** [comment]
Nice, can you update the documentation too?

**Comment by ramasilveyra** [comment]
@graingert you mean https://github.com/graingert/wowjs.uk right?

Because I added the new config feature to the example on the README.md: https://github.com/graingert/WOW/pull/6/files#diff-04c6e90faac2675aa89e2176d2eec7d8R99

**Comment by graingert** [comment]
I meant the examples/docs section on gh-pages. sadly wowjs.uk is in a separate repo because of trigger happy JS.org maintainers

**Comment by ramasilveyra** [comment]
@graingert docs update on https://github.com/graingert/WOW/pull/7

**Comment by graingert** [comment]
Looks good I'll sort this out after I get back from holiday

**Comment by ramasilveyra** [comment]
Now my last request, when you have time could you publish this last version to npm? I still see the 1.2.2 on https://www.npmjs.com/package/wow.js

Thanks @graingert!

**Comment by graingert** [comment]
yeah will do

**Comment by ramasilveyra** [comment]
**Just a friendly reminder** if you want, if you have time: could you publish to npm the v1.3.0 version?

Thanks in advance for your time.

**Comment by graingert** [comment]
@ramasilveyra oh woops I thought I'd released this.

**Pull request merged**
